defaults:
    - model: llada-base
    - generation: vanilla
    - cache: null
    - _self_

seed: 42
batch_size: ${dataset.batch_size}
attn_implementation: "eager" # sdpa or eager
dataset:
    name: null # make sure the name is in lm-eval task list
    size: null
    n_shot: null # null means using default few-shot setting from lm-eval
    system_prompt: null
    batch_size: 1 # for speed testing, always 1